#!/bin/sh
# Auto-generated package installation script
# Packages marked with KEEP tag in pkgbible.toml

sudo pacman -S --needed --noconfirm \
    cava \
    networkmanager \
    openssh \
    krita \
    pipewire-audio \
    hypridle \
    libreoffice-still \
    swaync \
    fish \
    rustup \
    uwsm \
    hyprpolkitagent \
    egl-wayland \
    ripgrep \
    snap-pac \
    todoman \
    xdg-desktop-portal-hyprland \
    alsa-utils \
    gtk4 \
    pipewire-pulse \
    snapper \
    starship \
    libnotify \
    nano \
    cliphist \
    clang \
    waybar \
    tig \
    vim \
    pavucontrol \
    power-profiles-daemon \
    wireplumber \
    qt5-wayland \
    git \
    kvantum-qt5 \
    slurp \
    pipewire \
    efibootmgr \
    man-pages \
    sudo \
    kvantum \
    linux-firmware \
    btop \
    neovim \
    btrfs-progs \
    gtk-engine-murrine \
    tree-sitter-cli \
    mold \
    sof-firmware \
    wl-clipboard \
    grim \
    ttf-nerd-fonts-symbols-mono \
    firewalld \
    ttf-liberation \
    texinfo \
    typst \
    grub-btrfs \
    pipewire-alsa \
    fastfetch \
    firefox \
    kitty \
    wayland-utils \
    qt6-wayland \
    cmake \
    man-db \
    onefetch \
    hyprlock \
    wev \
    7zip \
    imagemagick \
    fd \
    yazi \
    jq \
    resvg \
    fzf \
    python-tomlkit \
    unzip \
    hyprsunset \
    hyprpaper \
    alacritty \
    hyprland \
    tokei \
    helix
