# vim:ft=kitty

# @@dark_base@@
background #060002 
# @@txt_main@@
foreground #f071ae
# @@txt_sel@@
selection_background #00236d
# @@txt_white@@
selection_foreground #ffefef
# @@txt_green@@
url_color #53bf26
# @@txt_white@@
cursor #ffefef
# @@txt_dark@@
cursor_text_color #1f1f1f

# Tabs
# @@light_base@@
active_tab_background #ab3d77
# @@txt_main@@
active_tab_foreground #f071ae
# @@dark_main@@
inactive_tab_background #211111
# @@txt_pale@@
inactive_tab_foreground #cf3680
#tab_bar_background #15161e

# Windows
active_border_color #7aa2f7
inactive_border_color #292e42

# normal
# @@txt_pale@@
color0 #cf3680
# @@txt_red@@
color1 #d1261d
# @@txt_green@@
color2 #53bf26
# @@txt_yellow@@
color3 #f2e82e
# @@txt_blue@@
color4 #6287FC
# @@txt_purple@@
color5 #8351FC
# @@txt_cyan@@
color6 #82d4fC
# @@txt_pale@@
color7 #cf3680

# bright
# @@txt_pale@@
color8 #cf3680
# @@txt_red@@
color9 #d1261d
# @@txt_green@@
color10 #53bf26
# @@txt_yellow@@
color11 #f2e82e
# @@txt_blue@@
color12 #6287FC
# @@txt_purple@@
color13 #8351FC
# @@txt_cyan@@
color14 #82d4fC
# @@txt_pale@@
color15 #cf3680

# extended colors
# @@txt_orange@@
color16 #dF6350
# @@txt_red@@
color17 #d1261d