animations {
    enabled = true
    animation = fadeIn, 0, 1, default
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.1) # no fill

    # @@light_main, light_highlight@@
    outer_color = rgba(d15895ee) rgba(e172a8ee) 45deg
    # @@txt_blue, txt_purple@@
    check_color=rgba(6287FCee) rgba(8351FCee) 120deg
    # @@txt_red, txt_orange@@
    fail_color=rgba(d1261dee) rgba(dF6350ee) 40deg

    # outer_color = rgba(c961bdee) rgba(f7b5daee) 45deg
    # check_color=rgba(00ff99ee) rgba(ff6633ee) 120deg
    # fail_color=rgba(ff6633ee) rgba(ff0066ee) 40deg

    # @@txt_main@@
    font_color = rgb(f071ae)
    font_family = Mango
    fade_on_empty = false
    rounding = 8

    placeholder_text = <i>Password pls...</i>
    fail_text = DON'T TOUCH MY PC!

    zindex = 100
    position = 0, 96
    halign = center
    valign = bottom
}

background {
    monitor =
    path = /home/cephyr/pictures/background/amora-b-celeste-8.jpg
    # @@dark_main@@
    color = rgba(211111ff)
}

label {
    monitor =
    text = $TIME
    font_size = 32
    font_family = Mango
    # @@txt_main@@
    color = rgb(f071ae)

    position = 0, -48
    halign = center
    valign = top
}

label {
    monitor =
    text = Hi $USER
    font_size = 48
    font_family = Mango
    # @@txt_main@@
    color = rgb(f071ae)
    
    position = 0, -150
    halign = center
    valign = top
}

label {
    monitor =
    text = $TIME
    font_size = 32
    font_family = Mango
    # @@dark_main@@
    color = rgba(211111ff)

    zindex = -1
    position = 0, -56
    halign = center
    valign = top
}

label {
    monitor =

    text = Hi $USER
    font_size = 48
    font_family = Mango
    # @@dark_main@@
    color = rgba(211111ff)
    
    zindex = -1
    position = 0, -160
    halign = center
    valign = top
}