return {
	-- {
	-- 	"akinsho/bufferline.nvim",
	-- 	dependencies = "nvim-tree/nvim-web-devicons",
	-- 	config = function()
	-- 		require("bufferline").setup({
	-- 			options = {
	-- 				-- style_preset = require("bufferline").style_preset.minimal,
	--
	-- 				diagnostics = "nvim_lsp",
	-- 				diagnostics_indicator = function(count, level, diagnostics_dict, context)
	-- 					return count .. "!"
	-- 				end,
	--
	-- 				buffer_close_icon = "X",
	-- 				modified_icon = "M ",
	-- 				close_icon = " ",
	-- 				left_trunc_marker = "...",
	-- 				right_trunc_marker = "...",
	-- 				separator_style = "slant",
	--
	-- 				show_buffer_icons = false, -- disable filetype icons for buffers
	-- 				show_buffer_close_icons = false,
	-- 				show_close_icon = false,
	-- 				themable = true,
	--
	-- 				hover = {
	-- 					enabled = false,
	-- 				},
	-- 			},
	-- 		})
	-- 	end,
	-- },
}
